package betty-blocks:redirect@1.0.0;

interface redirect {
    type json-string = string;

    // This returns a json-string because the regular return type uses a list of tuples, which is unsupported
    redirect: func(redirect-URL: string) -> result<json-string, string>;
}

world main {
    export redirect;
}
    