[workspace]
members = ["functions/*/*"]

[workspace.package]
edition = "2024"

[workspace.dependencies]
wasmtime = { version = "45", default-features = false, features = ["component-model", "cranelift", "runtime", "std"] }
wasmtime-testing-helper = { path = "../wasmtime-testing-helper" }
wit-bindgen = "0.47.0"
