package betty-blocks:generate-uuid@1.0.0;

interface generate-uuid {
    record output {
        %uuid: string
    }

    generate-uuid: func() -> output;
}

world main {
    export generate-uuid;
}
    
