package betty-blocks:split-text@1.0.0;

interface split-text {
    split-all: func(text: string, split-by: string) -> list<string>;
    split-once: func(text: string, split-by: string) -> option<tuple<string, string>>;
}

world main {
    export split-text;
}

