[overrides]
"betty-blocks-utilities:types" = { path = "./external/types.wit" }
"betty-blocks-utilities:data-api" = { path = "./external/data-api.wit" }
"betty-blocks-types:types" = { path = "./external/types-v2.wit" }
"betty-blocks-types:data-api" = { path = "./external/data-api-v2.wit" }
"betty-blocks-types:upload-file" = { path = "./external/upload-file-v3.wit" }
