[overrides]
"betty-blocks-utilities:types" = { path = "./external/types.wit" }
"betty-blocks-utilities:data-api" = { path = "./external/data-api.wit" }
"betty-blocks-utilities:upload-file" = { path = "./external/upload-file.wit" }
